apiVersion: apps/v1
kind: Deployment
metadata:
  name: fresh-farm
  labels:
    app: fresh-farm
  annotations:
    argocd-image-updater.argoproj.io/image-list: freshfarm=docker.io/naveen561729/fresh-farm:latest
    argocd-image-updater.argoproj.io/freshfarm.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fresh-farm
  template:
    metadata:
      labels:
        app: fresh-farm
    spec:
      containers:
      - name: fresh-farm
        image: naveen561729/fresh-farm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
